config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,path: "",skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/about' => 'homes#about'
  get "/customers/:name/hide" => "homes#hide", as: "confirm_hide"
  patch "/customers/:name/withdraw" => "homes#withdraw", as: "withdraw_customers"

    scope module: "public" do
      resources :items, only: [:index, :show]
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
      resources :cart_items, only: [:index, :update, :destroy, :create]
      get 'orders/complete' =>'orders#complete'
      post '/orders/confirm' => 'orders#confirm'
      resources :orders, only: [:new, :create, :index, :show]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
      get '/customers/my_page' => 'customers#show', as: :my_page
      get '/customers/edit' => 'customers#edit'
      patch '/customers' => 'customers#update'
      get '/customers/hide' => 'customers#hide'
      patch '/customers/withdrawal' => 'customers#withdrawal'
      resources :order_history_details, only: [:show]
      end


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_history_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item, optional: true

  def subtotal
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  # enum is_deleted: { false: 0, true: 1 }


def active_for_authentication?
  super && (is_deleted == false)
end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_history_details, dependent: :destroy
    has_one_attached :image


    validates :name, presence: true
    validates :introduction, presence: true

    def get_image
        if image.attached?
          image
        else
            'no_image.jpg'
        end
    end

    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_history_details
    enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def edit
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def index
    @items = Item.all
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = 'You have created item successfully.'
      redirect_to admin_item_path(@item.id)
    else
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    flash[:hoge] = "You have updated book successfully."
    redirect_to admin_item_path(@item.id)
    else
    render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name,
                                 :introduction,
                                 :price,
                                 :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @orders = Order.all
    @order = Order.find(params[:id])
    @total = 0
    @order.shipping_cost = 800
    @order.total_payment = @total + @order.shipping_cost
    @order_history_details = @order.order_history_details
  end

  def order_params
    params.require(:order).permit(:customer_id,
                                  :postal_code,
                                  :address,
                                  :name,
                                  :shipping_cost,
                                  :total_payment,
                                  :payment_method)
  end

  def customer_params
    params.require(:customer).permit(:last_name,
                                     :first_name,
                                     :last_name_kana,
                                     :first_name_kana,
                                     :postal_code,
                                     :address,
                                     :telephone_number,
                                     :email,
                                     :customer_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    my_page_path
  end

  private

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,
                                                         :first_name,
                                                         :last_name_kana,
                                                         :first_name_kana,
                                                         :postal_code,
                                                         :address,
                                                         :telephone_number])
  end

  def after_sign_out_path_for(resource)
    root_path
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @item = Item.new
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/genres/edit.html.erb
<h1>Admin::Genres#edit</h1>
<p>Find me in app/views/admin/genres/edit.html.erb</p>

app/views/admin/genres/index.html.erb
<h1>Admin::Genres#index</h1>
<p>Find me in app/views/admin/genres/index.html.erb</p>

app/views/admin/orders/index.html.erb
<div class="container">
  <div claas="row">
    <div class="col-md-8 offset-md-1">
      <table>
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
              <td><%= order.created_at.to_s(:datetime_jp) %></td>
              <td><%= order.name %></td>
              <td><%= order.order_history_details.sum(:quantity) %></td>
              <td><%= link_to "表示する", admin_order_path(order.id), class:"btn btn-sm btn-primary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
<h3>注文履歴詳細</h3>
  <div claas="row">
    <div class="col-md-12 offset-md-1">
      <table>
          <tr>
            <th>購入者</th><td><%= @order.name %></td>
          </tr>
          <tr>
            <th>注文日</th><td><%= @order.created_at.to_s(:datetime_jp) %></td>
          </tr>
          <tr>
            <th>配送先</th><td><%= @order.address %></td>
          </tr>
          <tr>
            <th>支払方法</th><td><%= @order.payment_method %></td>
          </tr>
          <tr>
            <th>注文ステータス</th>
          </tr>
      </table>
    </div>
  </div>
  <div class="row">
      <div class="col-md-5 offset-md-1">
          <table class="items">
              <thead>
                  <tr>
                      <th>商品名</th>
                      <th>単価（税込）</th>
                      <th>数量</th>
                      <th>小計</th>
                      <th>制作ステータス</th>
                  </tr>
              </thead>
              <tbody>
                  <% @order_history_details.each do |order_history_detail| %>
                  <tr>
                      <td><%= order_history_detail.item.name %></td>
                      <td><%= order_history_detail.unit_price %></td>
                      <td><%= order_history_detail.quantity %></td>
                      <td><%= order_history_detail.unit_price * order_history_detail.quantity %></td>
                      <td></td>
                  </tr>
                  <% end %>
              </tbody>
          </table>
      </div>
  </div>
</div>