config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,path: "",skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/about' => 'homes#about'
  get "/customers/:name/hide" => "homes#hide", as: "confirm_hide"
  patch "/customers/:name/withdraw" => "homes#withdraw", as: "withdraw_customers"

    scope module: "public" do
      resources :items, only: [:index, :show]
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
      resources :cart_items, only: [:index, :update, :destroy, :create]
      get 'orders/complete' =>'orders#complete'
      post '/orders/confirm' => 'orders#confirm'
      resources :orders, only: [:new, :create, :index, :show]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
      get '/customers/my_page' => 'customers#show', as: :my_page
      get '/customers/edit' => 'customers#edit'
      patch '/customers' => 'customers#update'
      get '/customers/hide' => 'customers#hide'
      patch '/customers/withdrawal' => 'customers#withdrawal'
      resources :order_history_details, only: [:show]
      end


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_history_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item, optional: true

  def subtotal
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  # enum is_deleted: { false: 0, true: 1 }


def active_for_authentication?
  super && (is_deleted == false)
end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_history_details, dependent: :destroy
    has_one_attached :image


    validates :name, presence: true
    validates :introduction, presence: true

    def get_image
        if image.attached?
          image
        else
            'no_image.jpg'
        end
    end

    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_history_details
    enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def edit
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def index
    @items = Item.all
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = 'You have created item successfully.'
      redirect_to admin_item_path(@item.id)
    else
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    flash[:hoge] = "You have updated book successfully."
    redirect_to admin_item_path(@item.id)
    else
    render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name,
                                 :introduction,
                                 :price,
                                 :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @orders = Order.all
    @order = Order.find(params[:id])
    @total = 0
    @order.shipping_cost = 800
    @order.total_payment = @total + @order.shipping_cost
    @order_history_details = @order.order_history_details
  end

  def order_params
    params.require(:order).permit(:customer_id,
                                  :postal_code,
                                  :address,
                                  :name,
                                  :shipping_cost,
                                  :total_payment,
                                  :payment_method)
  end

  def customer_params
    params.require(:customer).permit(:last_name,
                                     :first_name,
                                     :last_name_kana,
                                     :first_name_kana,
                                     :postal_code,
                                     :address,
                                     :telephone_number,
                                     :email,
                                     :customer_id)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    my_page_path
  end

  private

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,
                                                         :first_name,
                                                         :last_name_kana,
                                                         :first_name_kana,
                                                         :postal_code,
                                                         :address,
                                                         :telephone_number])
  end

  def after_sign_out_path_for(resource)
    root_path
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @item = Item.new
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/homes/top.html.erb
<h1>管理者用top</h1>

<%= link_to "ログイン", new_admin_session_path %>

app/views/admin/items/edit.html.erb
<h1>Admin::Items#edit</h1>
<p>Find me in app/views/admin/items/edit.html.erb</p>

  <%= form_with model: @item,url:admin_item_path, method: :patch, local:true do |f| %>

　　<%= f.label :商品画像 %><br />
    <%= f.file_field :image, accept:"image/*" %><br />

    <%= f.label :商品名 %><br />
    <%= f.text_field :name %><br />

    <%= f.label :商品説明 %><br />
    <%= f.text_field :introduction %><br />

    <%= f.label :税抜価格 %><br />
　　<%= f.text_field :price, data: { autonumeric: {aSign: '¥ ', mDec: 0 } } %><br />

    <%= f.submit '編集内容を保存' %>
  <% end %>

app/views/admin/items/index.html.erb
<div class="container">
  <div claas="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>商品一覧</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>商品id</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name,"/admin/items/#{item.id}" %></td>
            <td><%= item.price %></td>
            <td></td>
            <td></td>
          </tr>
          <% end %>
        </tbody>
    </div>
  </div>
</div>
<p class="text-right"><%= link_to "新規登録", new_admin_item_path %></p>

app/views/admin/items/new.html.erb
<h1>New Item</h1>
<%= flash[:notice] %>
<%= form_with model: @item,url: admin_items_path do |f| %>

<%= f.label :商品画像 %><br />
<%= f.file_field :image, accept: "image/*" %><br />

<%= f.label :商品名 %><br />
<%= f.text_field :name %><br />

<%= f.label :商品説明 %><br />
<%= f.text_area :introduction %><br />

<%= f.label :税抜価格 %><br />
<%= f.text_field :price, data: { autonumeric: {aSign: '¥ ', mDec: 0 } } %>円<br />

<%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>
<div class="container mt-5 px-5 px-sm-0">
  <div class="row">
    <div class="col-4">
        <% if @item.image.attached? %>
        <%= image_tag @item.image, size: "300x250" %>
        <% else %>
        <%= image_tag 'no_image', size: "300x250" %>
        <% end %>
    </div><br />
    <div class="col-md-3 offset-md-1">
      <table>
        <tr>
          <th>商品名</th><td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th><td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>税込価格（税抜価格）</th><td><%= @item.with_tax_price %>(<%= @item.price %>)円</td>
        </tr>
      </table>
        <p></p>
        <%= link_to "編集する", edit_admin_item_path, class:"btn btn-sm btn-success" %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
     <div class="mx-auto justify-content-between">
      <h1>About</h1>
      <h4>ながのCAKEは全国発送可能なケーキ屋さんです。<br />
      お子様からお年寄りの方までお召し上がりいただけるよう、<br />
      様々なバリエーションをご用意しております。<br />
      また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br />
      ぜひご注文ください。</h4>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto justify-content-between">
      <p>ようこそ、ながのCAKEへ！<br />
      このサイトは。ケーキ販売のECサイトになります。<br />
      会員でない方も商品の閲覧はできますが、<br />
      購入には会員登録が必要になります。</p>
    </div>
  </div>
</div>

<div class="container">
  <div claas="row">
      <h1>新着商品</h1>
    <div class="d-flex justify-content-around">
      <table>
        <% @items.each do |item| %>
        <tr>
          <th><%= link_to item_path (item.id) do %>
          <%= image_tag item.get_image, size: "250x200" %>
          <% end %>
          </th>
          <td><%= link_to item.name,"/items/#{item.id}" %></td>
          <td><%= item.introduction %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<h1>商品一覧</h1>
<% @items.each do |item| %>
  <p><%= link_to item.name,"/items/#{item.id}" %></p>
  <p><%= item.introduction %></p>
<% end %>