config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,path: "",skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/about' => 'homes#about'
  get "/customers/:name/hide" => "homes#hide", as: "confirm_hide"
  patch "/customers/:name/withdraw" => "homes#withdraw", as: "withdraw_customers"

    scope module: "public" do
      resources :items, only: [:index, :show]
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
      resources :cart_items, only: [:index, :update, :destroy, :create]
      get 'orders/complete' =>'orders#complete'
      post '/orders/confirm' => 'orders#confirm'
      resources :orders, only: [:new, :create, :index, :show]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
      get '/customers/my_page' => 'customers#show', as: :my_page
      get '/customers/edit' => 'customers#edit'
      patch '/customers' => 'customers#update'
      get '/customers/hide' => 'customers#hide'
      patch '/customers/withdrawal' => 'customers#withdrawal'
      resources :order_history_details, only: [:show]
      end


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_history_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item, optional: true

  def subtotal
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  # enum is_deleted: { false: 0, true: 1 }


def active_for_authentication?
  super && (is_deleted == false)
end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_history_details, dependent: :destroy
    has_one_attached :image


    validates :name, presence: true
    validates :introduction, presence: true

    def get_image
        if image.attached?
          image
        else
            'no_image.jpg'
        end
    end

    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_history_details
    enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    my_page_path
  end

  private

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,
                                                         :first_name,
                                                         :last_name_kana,
                                                         :first_name_kana,
                                                         :postal_code,
                                                         :address,
                                                         :telephone_number])
  end

  def after_sign_out_path_for(resource)
    root_path
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
    @item = Item.new
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/79e328e066.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class ="container">
          <a class="navbar-brand" href="/">
            <span>NaganoCake</span>
          </a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
              <%= link_to admin_items_path, class: "nav-link text-light" do %>
              商品一覧
              <% end %>
              <%= link_to admin_customers_path, class: "nav-link text-light" do %>
              会員一覧
              <% end %>
              <%= link_to admin_orders_path, class: "nav-link text-light" do %>
              注文履歴一覧
              <% end %>
              <%= link_to admin_genres_path, class: "nav-link text-light" do %>
              ジャンル
              <% end %>
              <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>
              Log out
              <% end %>
            <% else %>
              <% if customer_signed_in? %>
              <%= link_to my_page_path, class: "nav-link text-light" do %>
              マイページ
              <% end %>
              <%= link_to items_path, class: "nav-link text-light" do %>
              商品一覧
              <% end %>
              <%= link_to cart_items_path, class: "nav-link text-light" do %>
              カート
              <% end %>
              <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link text-light" do %>
              Log out
              <% end %>
            <% else %>
            <%= link_to about_path, class: "nav-link text-light" do %>
              About
              <% end %>
              <%= link_to items_path, class: "nav-link text-light" do %>
              商品一覧
              <% end %>
              <%= link_to new_customer_registration_path, class: "nav-link text-light" do %>
              新規登録
              <% end %>
              <%= link_to new_customer_session_path, class: "nav-link text-light" do %>
              Log in
              <% end %>
            <% end %>
          <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
    <%= yield %>
    </main>
  </body>
</html>